### ISSUE TITLE
scrap next machtes

### ISSUE THREAD

**Issue by vto70** [gingeleski/odds-portal-scraper#1]
Is possible to scrab next matches, for exaample: http://www.oddsportal.com/soccer/germany/bundesliga/
thanks

**Comment by gingeleski** [comment]
Generally possible - yes.

With the code that's here already - probably not.

At this time there are now two example projects and I hope that one of them can be a useful resource for whoever wants to implement further scraping.

Closing this issue as out-of-scope.
