### ISSUE TITLE
Scraping actual odds by bookmaker vs. average odds?

### ISSUE THREAD

**Issue by zacharmentrout** [gingeleski/odds-portal-scraper#11]
Do you have any plans to add a feature that allows a user to scrape the actual odds offered by each bookmaker (e.g. each entry [here](https://www.oddsportal.com/basketball/usa/nba-2018-2019/utah-jazz-houston-rockets-65RBf5B1/)), versus the average odds across all bookmakers? Thanks.

**Comment by gingeleski** [comment]
Hi - thanks for your question and interest in the project.

Currently, any of the work under this repo scrapes average odds only, from the overall tables of results.

I will not be working on this in the foreseeable future but anyone's welcome to do so then pull request.
