### ISSUE TITLE
Could not read environment variable ODDS_PORTAL_USERNAME

### ISSUE THREAD

**Issue by obtim** [gingeleski/odds-portal-scraper#12]
Got error

(venv) c:\Helper\odds-portal-scraper\predictions>python scraper.py
Traceback (most recent call last):
  File "scraper.py", line 52, in main
    username = os.environ['ODDS_PORTAL_USERNAME']
  File "C:\Users\1\AppData\Local\Programs\Python\Python38\lib\os.py", line 673,
in __getitem__
    raise KeyError(key) from None
KeyError: 'ODDS_PORTAL_USERNAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scraper.py", line 135, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Users\1\AppData\Local\Programs\Python\Python38\lib\asyncio\base_event
s.py", line 612, in run_until_complete
    return future.result()
  File "scraper.py", line 54, in main
    raise RuntimeError('Could not read environment variable ODDS_PORTAL_USERNAME
')
RuntimeError: Could not read environment variable ODDS_PORTAL_USERNAME

What should I fix ?

**Comment by gingeleski** [comment]
Ideally there'd be exception handling there to spit out a nice message (my bad), but in this case the error's not too cryptic.

You should just set an environment variable with name `ODDS_PORTAL_USERNAME` and a value of your actual OddsPortal username via the terminal where you're running this.

https://www.twilio.com/blog/2017/01/how-to-set-environment-variables.html

**Comment by gingeleski** [comment]
I've updated the documentation to reflect this and help others. Thanks -- Randy
